# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format
    - name: Run dotnet format
      run: dotnet format atm --verify-no-changes --verbosity diagnostic
      
    - name: Restore dependencies
      run: dotnet restore atm
    - name: Build
      run: dotnet build atm --no-restore

    

      
    - name: Test
      run: dotnet test atm --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        file: coverage.opencover.xml
        directory: atm/atm-test
        token: ${{ secrets.CODECOV_TOKEN }}
  
  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Upload to gdrive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.credentials }}
        filename: "README.md"
        folderId: ${{ secrets.folderId }}
        overwrite: "true" # optional boolean
